# Generated by Django 4.2.2 on 2023-07-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=7)),
                ('first_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=100)),
                ('passout', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('testimonial', models.ImageField(upload_to='testimonials/')),
                ('profile', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
