# Generated by Django 4.2.2 on 2023-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinatorname', models.CharField(max_length=100)),
                ('coordinatormailid', models.CharField(max_length=100)),
                ('coordinatorpassword', models.CharField(max_length=100)),
                ('coordinatordepartment', models.CharField(max_length=30)),
            ],
        ),
    ]
