# Generated by Django 4.2.2 on 2023-07-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=30),
            preserve_default=False,
        ),
    ]
