# Generated by Django 4.2.3 on 2023-08-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='type',
        ),
    ]
